/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsesoriasRouteImport } from './routes/asesorias'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ProgramaRouteImport } from './routes/programa'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsesoriasRoute = AsesoriasRouteImport.update({
  id: '/asesorias',
  path: '/asesorias',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramaRoute = ProgramaRouteImport.update({
  id: '/programa',
  path: '/programa',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asesorias': typeof AsesoriasRoute
  '/blog': typeof BlogRoute
  '/contacto': typeof ContactoRoute
  '/programa': typeof ProgramaRoute
  '/recursos': typeof RecursosRoute
  '/sobre-mi': typeof SobreMiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asesorias': typeof AsesoriasRoute
  '/blog': typeof BlogRoute
  '/contacto': typeof ContactoRoute
  '/programa': typeof ProgramaRoute
  '/recursos': typeof RecursosRoute
  '/sobre-mi': typeof SobreMiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asesorias': typeof AsesoriasRoute
  '/blog': typeof BlogRoute
  '/contacto': typeof ContactoRoute
  '/programa': typeof ProgramaRoute
  '/recursos': typeof RecursosRoute
  '/sobre-mi': typeof SobreMiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asesorias'
    | '/blog'
    | '/contacto'
    | '/programa'
    | '/recursos'
    | '/sobre-mi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asesorias'
    | '/blog'
    | '/contacto'
    | '/programa'
    | '/recursos'
    | '/sobre-mi'
  id:
    | '__root__'
    | '/'
    | '/asesorias'
    | '/blog'
    | '/contacto'
    | '/programa'
    | '/recursos'
    | '/sobre-mi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsesoriasRoute: typeof AsesoriasRoute
  BlogRoute: typeof BlogRoute
  ContactoRoute: typeof ContactoRoute
  ProgramaRoute: typeof ProgramaRoute
  RecursosRoute: typeof RecursosRoute
  SobreMiRoute: typeof SobreMiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asesorias': {
      id: '/asesorias'
      path: '/asesorias'
      fullPath: '/asesorias'
      preLoaderRoute: typeof AsesoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa': {
      id: '/programa'
      path: '/programa'
      fullPath: '/programa'
      preLoaderRoute: typeof ProgramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsesoriasRoute: AsesoriasRoute,
  BlogRoute: BlogRoute,
  ContactoRoute: ContactoRoute,
  ProgramaRoute: ProgramaRoute,
  RecursosRoute: RecursosRoute,
  SobreMiRoute: SobreMiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
